environments:
  staging:
    url: http://beta.chalmers.it
    branch: staging
    javascripts:
      - jquery.smoothscroll
      - jquery.autosize
      - jquery.tipsy
      - jquery.modal
      - chalmersit.courses
      - chalmersit

  live:
    url: http://live.chalmers.it
    branch: live
    commit_message: "[auto] Compile CSS and JS"
    javascripts:
      - all